export const data = [
  {
    name: "react",
    full_name: "facebook/react",
    stargazers_count: "190.121",
    forks: 39.152,
    open_issues: 59,
    language: "HTML",
    license: "MIT",
    age: "9 years ago",
    lastCommit: "9 years ago",
    owner: {avatar_url: "https://avatars.githubusercontent.com/u/5550850?v=4"}
  },
  {
    name: "vue",
    full_name: "vuejs/vue",
    stargazers_count: "190.121",
    forks: 39.152,
    open_issues: 59,
    language: "HTML",
    license: "MIT",
    age: "9 years ago",
    lastCommit: "9 years ago",
  },
  {
    name: "angular",
    full_name: "angularjs/angular",
    stargazers_count: "190.121",
    forks: 39.152,
    open_issues: 59,
    language: "HTML",
    license: "MIT",
    age: "9 years ago",
    lastCommit: "9 years ago",
  },
];